language: r

r:
  - release 

cache: packages  

before_install:
  - Rscript -e 'install.packages(c("devtools", "testthat"))' 

script:
  - Rscript -e 'testthat::test_dir("tests/")'  

notifications:
  email:
    on_success: change  
    on_failure: always  