language: r

cache: packages  # Caches installed R packages to speed up builds

r:
  - release  # Use the latest stable R version

r_packages:
  - testthat  # Required for running tests
  - devtools  # Helpful for package development

script:
  - R CMD build .  # Build the package
  - R CMD check *tar.gz --as-cran  # Run package checks
  - Rscript -e 'library(testthat); testthat::test_dir("cryptoR/tests/testthat")'
notifications:
  email:
    on_success: change  # Notify only on status change
    on_failure: always  # Always notify on failure