language: r

r:
  - release  # Use the latest stable R version

r_packages:
  - testthat  # Required for running tests
  - devtools  # Helpful for package development

script:
  - R CMD build .  # Build the package
  - R CMD check *tar.gz --as-cran  # Run package checks
  - Rscript -e 'library(testthat); testthat::test_dir("cryptoR/tests/testthat")'