name: R-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies (for R packages)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install `remotes` (lighter than devtools)
        run: |
          R -e 'install.packages("remotes", repos="https://cloud.r-project.org")'

      - name: Install dependencies (manual workaround)
        run: |
          R -e 'remotes::install_cran(c("testthat", "httr",“ggplot2”,"dplyr", "TTR", "roxygen2", "pkgload"))'

      - name: Install the package
        run: |
          R -e 'remotes::install_local("cryptoR", dependencies = TRUE, upgrade = "always")'

      - name: Run tests
        run: Rscript -e 'library(testthat); library(cryptoR); testthat::test_dir("cryptoR/tests/testthat")'
