name: R-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install `pak` manually (fix dependency error)
        run: |
          R -e 'install.packages("pak", repos="https://cloud.r-project.org")'

      - name: Install dependencies (manual workaround)
        run: |
          R -e 'install.packages(c("testthat", "devtools", "httr", "dplyr", "TTR"))'

      - name: Install the package
        run: |
          R -e 'devtools::install(".")'

      - name: Run tests
        run: Rscript -e 'library(testthat); library(cryptoR); testthat::test_dir("cryptoR/tests/testthat")'
