name: R-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages(c("testthat", "devtools", "httr", "dplyr"))'

      - name: Run tests
        run: Rscript -e 'library(testthat); testthat::test_dir("cryptoR/tests/testthat")'
